### ISSUE TITLE
[design-proposal] Add method for modifying attributes based on channels

### ISSUE THREAD

**Issue by jerryaldrichiii** [chef/effortless#101]
Previous patterns of using Chef allowed for setting attributes based on `environment`/`policy_group`. In the Effortless pattern though both constructs cease to exist.

We need a way to configure attributes based on environments and/or channesl. For example, setting a syslog server for Production to be different than in Dev.

One way we could do this is keying off a known attribute at run time (e.g. `node['effortless']['channel']` or `node.effortless_channel`). Then setting that via `user.toml`.

Let's discuss this and other options!

> NOTE: Feel free to edit this to make more sense/add a TL;DR

**Comment by jonlives** [comment]
In an ideal world, I'd love to see us be able to support this with attribute hoisting a-la https://github.com/chef-boneyard/chef-rfc/blob/master/rfc105-attribute-hoist.md - not sure how possible this would be given the need to compile the policyfile at build time though.

**Comment by danielcbright** [comment]
I think this would be great if it still lived in the policyfile as a case statement like most folks currently do.  Maybe via env variable? For example, if you want certain attributes to be different if running in Test Kitchen you can do something like this:

```
if ENV['TEST_KITCHEN']
  default['param']['name'] = node['test']['value']
else
  default['param']['name'] = node['real']['value']
end
```

If maybe during run we do some trickery to export a var based on a command that reads it's own information this would work? Or even better, if the channel name is exposed already via a handlebar helper then we could just export the var from there... just thinking out loud

**Comment by TheLunaticScripter** [comment]
I'd like to understand more about what those types of attributes are used for. Also, another question is are we talking about a few or hundreds of attributes. Currently, the scaffolding has the `attributes.json` convention that allows you to set attributes at run time by using the `user.toml`. It is my option that the `user.toml` should be tracked in source control with the provisioner. Looking at the reference for Habitat it doesn't look like channel is a variable that can be used by the package. but it does look like we might be able to use the `service group`  instead. I would need to test it but in provisioning, you would set the service group and then in the `attributes.json` use the mustache character for an attribute. You would also want to use channels for promotions of packages IMO.

**Comment by jerryaldrichiii** [comment]
@danielcbright it's a bit more than just "Am I in Kitchen or not". Here is a slightly more real world example:

```ruby
case node.policy_group
when 'dev'
  node.default['my_cookbook']['api_url'] = 'https://dev.example.com/api'
when 'staging'
  node.default['my_cookbook']['api_url'] = 'https://staging.example.com/api'
when 'production'
  node.default['my_cookbook']['api_url'] = 'https://prod.example.com/api'
end
```

That logic won't work however in a Policyfile.rb because the logic is evaluated at build time.

@jonlives I'm a fan of setting the attributes in cookbooks rather than hoisting for a few reasons. Mainly:
  - It matches the older Chef patterns so those who usually look in recipes/attribute files for attributes will not be surprised
  - It sets the attributes near where they are used
  - It's more intuitive than hoisting (100% personal opinion)

That being said...I think it might make more sense to use hoisting in Effortless given the structure of the package...I'll have to think more on it.

@TheLunaticScripter I'm not sure what the need is for attributes from users. Usually I only see a handful out in the field and they are related to things like selecting the correct logging server, or adding trial licenses vs production licenses. I'm not convinced that these issues can't be solved via Habitat directly, but having support for this would make migrations easier in the meantime.

I also agree that the `user.toml` or `attributes.json` should 100% be tracked in source. That is the only gripe I have about the method I laid out in the original post. No more spooky action at runtime!

**Comment by kenmacleod** [comment]
Just a comment from the peanut gallery:  supporting hoisting would make migrating existing policyfile users into Effortless a lot easier.  If we have to change the `policy_group` names to more Hab/Effortless-friendly channel names, that's a low impact change --- we add/change policy groups all the time.  If we have to change the logic for loading per-channel attributes, that's a big impact.

**Comment by echohack** [comment]
Hello @jerryaldrichiii 

In order for us to move forward with our design-proposal process, please edit your original (OP) comment and submit it in this form outlined here: https://github.com/chef/chef-oss-practices/blob/bc374ecaa5d0236f8dde3e92dfa5964bac43e2e5/contributors/guide/design-proposals.md

Thank you <3

**Comment by jerryaldrichiii** [comment]
@echohack I'm a bit swamped at the moment and don't know if I can get to this anytime soon. Are you up to edit the original message? I trust your judgement.

**Comment by emachnic** [comment]
This is definitely something I'd be interested in helping flesh out the use cases. @echohack do you need a design proposal according to the guidelines or will this one suffice?

**Comment by TheLunaticScripter** [comment]
Close in favor of #154.
