### ISSUE TITLE
[Tracking] [scaffolding-chef-infra] [scaffolding-chef-inspec] Bubble up variable as scaffold_log="level"

### ISSUE THREAD

**Issue by echohack** [chef/effortless#102]
When we run into issues there should be a way to specify the log level, in order to debug issues for all underlaying tools, without needing to rebuild the scaffolding.

**Comment by TheLunaticScripter** [comment]
I believe that we already have this for both `scaffolding-chef-infra` and `scaffolding-chef-inspec`. You can change the log level by setting the `log_level` to the desired level using a `user.toml` `default.toml` or by applying just that configuration with a `hab config apply`.

**Comment by echohack** [comment]
we do not have the ability to do this for all tools.
