### ISSUE TITLE
[scaffolding-chef-infra] [scaffolding-chef-inspec] Proxy issues with Effortless Build tools in Studio

### ISSUE THREAD

**Issue by echohack** [chef/effortless#104]
As a user behind a corporate firewall and proxying requests to the internet, I need to be able for Effortless to proxy all requests from build tools (such as Chef-DK) to use a custom CACert chain at build time.

**Comment by sam1el** [comment]
Adding information as requested.

http_proxy
https_proxy
SSL_CERT_FILE
The above environments variables have been set. Corporate cert gets through all other proxy settings until scaffolding tries to reach supermarket.

We need a feature for hab pkgs to utilize the hab cert chain.

Chef-dk currently cannot reach through a corporate proxy due to it not seeing the valid certs. Hab itself is functioning as expected.

This is the current error
```
✗✗✗ the handshake failed: The OpenSSL library reported an error: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:s3_clnt.c:1269:: unable to get local issuer certificate
✗✗✗
```

**Comment by echohack** [comment]
Here's a more detailed log showing `chef install --debug` occuring within the scaffolding.

```
[2019-07-26T15:14:52+00:00] ERROR: SSL Validation failure connecting to host: s3.amazonaws.com - SSL_connect returned=1 errno=0 state=error: certificate verify failed
Error: Failed to generate Policyfile.lock
Reason: (OpenSSL::SSL::SSLError) SSL Error connecting to https://supermarket.chef.io/api/v1/cookbooks/cloudcli/versions/1.2.0/download - SSL Error connecting to https://s3.amazonaws.com/community-files.opscode.com/cookbook_versions/tarballs/21168/original/cloudcli.tgz?1493505782 - SSL_connect returned=1 errno=0 state=error: certificate verify failed

/hab/pkgs/chef/chef-dk/3.0.38/20180525172209/ruby/2.4.0/gems/chef-14.1.12/lib/chef/http.rb:451:in `rescue in retrying_http_errors'
/hab/pkgs/chef/chef-dk/3.0.38/20180525172209/ruby/2.4.0/gems/chef-14.1.12/lib/chef/http.rb:408:in `retrying_http_errors'
/hab/pkgs/chef/chef-dk/3.0.38/20180525172209/ruby/2.4.0/gems/chef-14.1.12/lib/chef/http.rb:365:in `send_http_request'
/hab/pkgs/chef/chef-dk/3.0.38/20180525172209/ruby/2.4.0/gems/chef-14.1.12/lib/chef/http.rb:```

**Comment by echohack** [comment]
Workaround:

You can append your RootCA to this file in the studio:

`/hab/pkgs/core/cacerts/2018.12.05/20190115014206/ssl/certs/cacert.pem `

to work around this issue.

It's clear that we need to provide some mechanism in the studio / in effortless for handling this issue better, along with giving better error messages for what the user is encountering.

**Comment by dmccown** [comment]
We will have some changes coming soon with Habitat and how it handles Certs. This may help you out. Here's the issue we have in flight: https://github.com/habitat-sh/habitat/pull/6759
