### ISSUE TITLE
[scaffolding-infra-chef] Allow injecting SSL certs for `chef` commands

### ISSUE THREAD

**Issue by jerryaldrichiii** [chef/effortless#111]
For example, allowing the use of a custom SSL cert file for fetching from an on prem Artifactory.

**Comment by echohack** [comment]
@jerryaldrichiii I think this could be a great feature. Can you provide an error log that you're receiving? That way we can create a negative test case for this, and then make it pass as we develop this feature in the future.

**Comment by echohack** [comment]
This is a dupe of #104
