### ISSUE TITLE
[scaffolding-chef-inspec] Add scaffold_cacerts option to inspec scaffolding

### ISSUE THREAD

**Issue by jvogt** [chef/effortless#120]
Just as we do in effortless-chef-infra, it would be nice to be able to append custom ca certs.

**Comment by TheLunaticScripter** [comment]
#122

**Comment by TheLunaticScripter** [comment]
@jvogt This should be fixed in the latest unstable build can you test that you are able to perform replace the cert and report to Automate with an internal cert.

**Comment by echohack** [comment]
This is merged and will be released shortly. @jvogt can you test and close this issue if this is what you're looking for?

**Comment by jvogt** [comment]
Will test shortly

**Comment by jvogt** [comment]
Thank you @echohack!!! Worked without a hitch (linux).
