### ISSUE TITLE
Interval and splay suggestion for Inspec.

### ISSUE THREAD

**Issue by sam1el** [chef/effortless#146]
With the audit cookbook, you were able to send reports to automate with interval and splay much like you would in the chef-client. The major difference was, you could do it in minutes rather than seconds. This was pretty handy for not only space saving but, being able to report in intervals of 4 times a day, 2 times or 1 time per 24h. Many places I've worked preferred daily as well as a few customers. The current documentation for Effortless Inspec appears to want it in seconds in the `default.toml`. Typing it in seconds should work but, seems kinda weird for a 24hr interval

**Comment by echohack** [comment]
Hey @sam1el 

We've talked about modifying the interval/splay for both Chef Infra and Chef InSpec for performance reasons, but this would be a big change and require an epic and design proposal. Essentially, this boils down to building a small eventing system so we can execute the run hook or chef-client or inspec based on other events firing. We're not quite ready to tackle that kind of work yet.

In terms of changing this to minutes, Effortless looks to the upstream configuration and uses that. InSpec uses seconds, and therefore we use seconds. We won't be reproducing the behavior of the audit cookbook, unless it follows the same standard.

I'm closing this issue for now, we'll want to have a deeper conversation around this later when we consider the epic for eventing down the road.

**Comment by sam1el** [comment]
Makes perfect sense when broken down this way. Thank you for the info.
