### ISSUE TITLE
[scaffolding-chef-infra] Build from studios on separate drives on windows persist in hart

### ISSUE THREAD

**Issue by smford22** [chef/effortless#150]
Customer built a package and the studio mounted at `D:\...` when the `hart` file runs on a separate studio all of the `hab` paths point to `D:\hab\svc\...` rather than `C:\hab\svc` I will try to provide more information but wanted to get this tracked.

**Comment by TheLunaticScripter** [comment]
Blocked due to the FSROOT issue in habitat should be part of the 0.85.0 release.

**Comment by TheLunaticScripter** [comment]
@scottford-io can we check that this is fixed after the `0.85.0` release?

**Comment by drakoswraith** [comment]
For anybody that needs a workaround while the bug is worked on, I have found that using symlink from c:\src\... to d:\src... does work around this issue (as long as you obviously then enter the path from c:\). Hab will then use the normal paths on c: for the cache, studios, etc....  I've used that successfully from inside a HyperV VM as well with a shared local drive:

```
# locally
New-Item -ItemType SymbolicLink -Path "c:\src" -Target "d:\src"

# in VM
New-Item -ItemType SymbolicLink -Path "c:\src" -Target "\\tsclient\d\src"
```

**Comment by TheLunaticScripter** [comment]
@drakoswraith So this is still an issue even with the latest habitat? this is an issue with while in the studio the plan will add the studio FSROOT to the path of packages. It is my understanding that the FSROOT problem has been fixed can you confirm that with the latest habitat.

**Comment by drakoswraith** [comment]
Sure. I just upgraded yesterday after seeing the announcements in the effortless channel.  I'll see if i can duplicate it.

**Comment by drakoswraith** [comment]
Ok. I think it's good.  I built https://github.com/drakoswraith/habplan_portqryv2 and the binlinked package worked correctly.  Contents of the hart file didn't show any wrong paths.  I don't recall which plans i was testing before when i ran into it so i can't test the original one i had the issue with.

**Comment by TheLunaticScripter** [comment]
Sweet thanks for the update!
