### ISSUE TITLE
[scaffolding-chef-inspec|config] Feature Request - `node_name`

### ISSUE THREAD

**Issue by danielcbright** [chef/effortless#162]
This is a feature request to add the `node_name` variable to be able to be configured via the `default.toml` and `user.toml` for the `automate` config portion of the InSpec and Config files.

**Comment by TheLunaticScripter** [comment]
@danielcbright can you outline a bit more the problem that you are trying to solve with this?

**Comment by TheLunaticScripter** [comment]
I don't think this is the right place for this change to occur. IMO controlling the node name is something that should be done on the host directly and not a configurable feature from effortless.
