### ISSUE TITLE
Add support for --insecure option when pulling profiles from compliance server

### ISSUE THREAD

**Issue by gsloan-chef** [chef/effortless#183]
### Describe the Enhancement:
Effortless audit package builds fail when Automate is using a self-signed certificate

### Describe the Need:
I need a way to optionally allow `inspec compliance login` to run with the `--insecure`

### Current Alternative
There may be an alternative of building a custom ca-certs package but I have not explored it

### Can We Help You Implement This?:
I believe I have an implementation that works

**Comment by TheLunaticScripter** [comment]
So this looks like a simple fix but I think it would be good to look at whether we can get the ssl stuff to work as well. Just for replication is this an Automate instance with a self-signed cert or an issue with an internal CA?

**Comment by TheLunaticScripter** [comment]
This should be complete as of 0.20.0
