### ISSUE TITLE
Support running Effortless package on same host as older Chef Client version

### ISSUE THREAD

**Issue by scottvidmar** [chef/effortless#190]
## Motivation

As a user leveraging older version(s) of Chef Infra Client, I would like to be able to run Chef Infra Client via Habitat alongside my older Client versions. This would allow me to decouple application deployment cookbooks from baseline configuration cookbooks to be able to update them separately.

## Specification

For this, we would need to change scaffolding to support running Chef Client in a separate path from the default, and allow configuration of lockfile location. There may be additional changes required elsewhere to support this.

## Downstream Impact

This will impact Chef Client effortless scaffolding, but the idea is to keep the customer experience the same.

**Comment by TheLunaticScripter** [comment]
I'm not sure this is a good idea. I think running two chef clients will cause more pain than good.
