### ISSUE TITLE
[scaffolding-chef-infra] CACerts in scaffolding may be override bundled Ruby certs

### ISSUE THREAD

**Issue by echohack** [chef/effortless#20]
The scaffolding is currently pulling its own CACert bundle in, which may be undesired behavior because it may be overwriting the bundled CACerts in Ruby that the chef-client package delivers.

We need to investigate this further to prove it is true and create a replication case.

If this is true, we may be able to remove this: https://github.com/chef/scaffolding-chef/blob/master/scaffolding-chef/lib/scaffolding.sh#L81

**Comment by TheLunaticScripter** [comment]
I think this is not the desired behavior as it give customers an interface to add their own customer cert for uploading to Automate.
