### ISSUE TITLE
Make inspec and chef-client binary paths more explicit

### ISSUE THREAD

**Issue by jonlives** [chef/effortless#200]
## Description
In the scaffolding run hooks we invoke chef-client and inspec binaries from the path (ie https://github.com/chef/effortless/blob/master/scaffolding-chef-infra/lib/linux/run.bash#L32). We should make that more specific so that in the case of there being an existing chef-client or inspec binary present on the system we guarantee that the binary contained in the scaffolding will be used.

## Scaffolding Version
0.17.0

## Platform Version
This issue is present for the chef-infra scaffolding on Linux, and the chef-inspec scaffolding on both Linux and Windows

**Comment by jvogt** [comment]
When supervisor runs a service, isn't $PATH is always built with only `/hab/...` directories? Just curious how you would foresee a situation where the system `chef-client` is used?

**Comment by TheLunaticScripter** [comment]
this should be good now @jvogt  that should be fine but this is more a cause of being fully sure that the client being called is explicitly the one that was packaged with habitat at build time.
