### ISSUE TITLE
scaffolding-chef-inspec: Path is not set properly for Inspec bins when specifying alternate scaffold_inspec_client

### ISSUE THREAD

**Issue by collinmcneese** [chef/effortless#206]
## Description

On Windows, when attempting to specify an alternate `scaffold_inspec_client` using `scaffolding-chef-inspec`, the `$env:PATH` is not properly set to the correct location which prevents the Habitat service from being able to find the Inspec bin file.

This issue is hidden because if you are using the default `chef/inspec` for `scaffold_inspec_client`, it has a dependency on `chef/ruby-plus-devkit` which will properly update the path.

It looks like the logic which generates the run hook for the inspec scaffold is very different than what is being done for the infra scaffolding

## Scaffolding Version

`0.18.0`

## Platform Version

Windows Server 2016

## Replication Case

Attempt to use the scaffolding with `stuartpreston/chef-client-detox`

## Build or Run Output

```
inspec_wrapper.default(SV): Starting service as user=vagrant, group=<anonymous>
inspec_wrapper.default(E): Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Version"
.
inspec_wrapper.default(E): At line:38 char:8
inspec_wrapper.default(E): +     if([Version](inspec --version) -gt [Version]"4.17.27"){
inspec_wrapper.default(E): +        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
inspec_wrapper.default(E): + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
inspec_wrapper.default(E): + FullyQualifiedErrorId : ConvertToFinalInvalidCastException
inspec_wrapper.default(E):
```

**Comment by collinmcneese** [comment]
I'm about to put in a PR which fixes this as well, just wanted to tie it to an issue

**Comment by collinmcneese** [comment]
#207

**Comment by TheLunaticScripter** [comment]
this is fixed in master and will be in the next release of the scaffolding

**Comment by collinmcneese** [comment]
@TheLunaticScripter  -- Yep, this fixes the issue!

**Comment by TheLunaticScripter** [comment]
Sweet this is now in stable
