### ISSUE TITLE
Add support for hab plan init

### ISSUE THREAD

**Issue by echohack** [chef/effortless#22]
As a chef user with existing cookbooks and a policyfile, I expect `hab plan init` to automatically detect the repo type and generate all of the files necessary to get started.

**Comment by sam1el** [comment]
Currently I need an easy way to generate effortless packages. I currently have a hacked up version of the chef generate command that is doing it. It would be nice to have something like `hab plan init` rather than using the chef-workstation generator..

**Comment by sam1el** [comment]
Adding as requested
https://github.com/sam1el/chef_generator
