### ISSUE TITLE
Bash-style string comparison causes acceptance check to fail

### ISSUE THREAD

**Issue by gscho** [chef/effortless#234]
## Description

The run hook uses bash-style comparison when checking for the license acceptance.
This is an issue because the shebang is `!#/bin/sh" and the systems env gets added to the package path. 

On ubuntu 16.0.4, we see an error print out in our journal `run: 19: [: undefined: unexpected operator`

Default /bin/sh setup on ubuntu 16.04:

```
file `which sh`
/bin/sh: symbolic link to dash
```

## Scaffolding Version
chef/scaffolding-chef-infra/0.20.0/20200425115239

## Platform Version
Ubuntu 16.04

## Replication Case
Execute the generated run hook on a ubuntu 16.04 box

## Build or Run Output

```
./run: 19: [: undefined: unexpected **operator**
```

**Comment by TheLunaticScripter** [comment]
This should be fixed and in the current channel in review, I think a better way to fix this is to use the core/bash package that ships with habitat to ensure that this isn't a problem for other Linux distros with something else. I've opened a separate issue for that and will try and get that out in the next release.

**Comment by gscho** [comment]
Yeah I was thinking about that too, adding the bash pkg and setting the shebang to the hab-supplied bash. Just didn't want to start messing with pkg_deps

**Comment by TheLunaticScripter** [comment]
totally understand
