### ISSUE TITLE
Add support for on-prem depot

### ISSUE THREAD

**Issue by echohack** [chef/effortless#24]
As a user of scaffolding-chef, a major blocker for me is the on-prem builder. The main problems are as follows:

• Auth is a bit alpha/beta-y for A2-oauth and that's really what the customer wants to use, but is for now using local users to suffice/get past that issue.
• The sync script that comes with it is very finicky and there are a lot of issues when using self-signed/on-prem CA bundles that require you to go into the script and hack things to make it work.
• The documentation is lacking very straight forward/step-by-step installation and setup instructions (I'm working on that right now).
• Keeping the depot synced with the on-prem script doesn't work properly, and the bldr_package_sync go binary that is maintained by Indellient has a lot of bugs/issues as well.
• We now have things in `chef/` for effortless scaffolding, and the script doesn't pull/sync that stuff.

I don't want to use the public depot to host my own packages, and taking 2+ weeks to get the local depot sorted is not delightful at all.

**Comment by TheLunaticScripter** [comment]
I believe there is work ongoing to help fix up the on-prem builder and make this better. This is more than just an issue for effortless but for all habitat packages.
