### ISSUE TITLE
[Tracking] [scaffolding-chef-infra] Windows doesn't honor $pkg_deps set in scaffold

### ISSUE THREAD

**Issue by ncerny** [chef/effortless#26]
# Describe the problem
When using the scaffolding for windows, $pkg_deps is not set, resulting in the artifact not being able to find `$scaffold_chef_client`.

## Software Version
chef/scaffolding-chef 0.6.0 (echohack's build in depot)
hab 0.82.0
hab-sup 0.82.0

## Replication Case
Create a minimal plan.ps1 that does not include $pkg_deps, and attempt to execute the built package on Windows.

**Comment by ncerny** [comment]
In an apparently related issue, $pkg_svc_user isn't honored either -- when I don't set it directly, it seems to run as my user, but Chef-Client states that it's running as a non-administrative user.

**Comment by echohack** [comment]
Hey @ncerny thanks for opening this (and other issues) here.

This issue directly relates to a problem with Habitat scaffolding on Windows here: https://github.com/habitat-sh/habitat/issues/6671

I'll keep this open as a tracking issue and close other issues.

**Comment by TheLunaticScripter** [comment]
This is fixed in habitat 1.5.0.
