### ISSUE TITLE
[scaffolding-chef-infra] Chef-client needs access to binaries outside of Habitat context

### ISSUE THREAD

**Issue by echohack** [chef/effortless#42]
Currently the chef-client only uses binaries available to Habitat, and this can result in surprising results, such as using Busybox's version of APT / RPM instead of the one installed on the box.

InSpec has resolved this issue previously and we may adopt a similar solution here. Will need to have some discussion around this issue.

Reference:

https://github.com/inspec/inspec/pull/3645
https://github.com/inspec/inspec/blob/master/habitat/plan.sh#L67
https://github.com/inspec/inspec/issues/3635

**Comment by echohack** [comment]
Some top the head thoughts:

It's sometimes desirable to bundle a binary with your hab-managed-chef package so that you can ensure that chef-client executes THAT one. For example, say you wanted to have your chef cookbooks run against the newest Powershell, but you don't want to override the System's Powershell -- you could simply dep on Powershell and voila!

So maybe, what we do is iterate over the `pkg_deps` list and then statically link the deps that are only N-depth into the path like so:

```export PATH="/hab/pkgs/core/openssl/1.0.2q/20190115014220/bin/openssl/:/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:$PATH"```

Since the path finds binaries in PATH order (first wins).

As part of that setting you could allow folks to ignore linking the PATH entirely and only use the binaries in Habitat, if they really wanted to include every single dependency and make their plans platform specific, though this probably isn't a good idea.

Still need to noodle on it some more, curious what everyone else thinks.

**Comment by TheLunaticScripter** [comment]
I think this is done using the chef config file.
