### ISSUE TITLE
[Tracking][scaffolding-chef-infra] Add support for self-signed certificates for data collector reporting into Chef Automate

### ISSUE THREAD

**Issue by echohack** [chef/effortless#44]
This is a tracking issue to support self-signed certificates for using a data collector token to report runs into Chef Automate.

Resolving this issue may include:

- Modifying the init hook to accept an optional public certificate to be bundled with the package, for the purpose of ssl verification
- Testing with a real customer environment to validate the use case

-------------------------------------------------------------------------------

As a work around, I've been using my ssl_cacert_hack cookbook. Basically it expects to be wrapped and the wrapper cookbook to provide a ca-bundle.crt file in my_wrapper/files/default/ca-bundle.crt (for example), and links all of the cert files in /opt and /hab (configurable) to your "system" cabundle (ubuntu and centos have different paths).

Including this first in my runlist works, and we have nodes in A2! It seems a bit hamfisted... but it solved my problem... so "if it's dumb and it works..."?

See also: https://github.com/habitat-sh/core-plans/issues/1799

**Comment by jonlives** [comment]
This would be a great feature to add - currently any customers using internal SSL cert chains for A2 will need to fork the scaffolding to be able to use their own cacerts package. The customer I'm currently working with has built their own cacerts habitat package, so even allowing for this to be optionally specified at app build time (if possible) might be nice

**Comment by smford22** [comment]
Huge 👍 on this one. Has been on the radar since day one.
