### ISSUE TITLE
[Tracking] Test Kitchen Local Dev Workflow

### ISSUE THREAD

**Issue by echohack** [chef/effortless#62]
This is a tracking issue to document a test kitchen local dev workflow with Effortless.

**Comment by echohack** [comment]
@jerryaldrichiii Does the work you've added close this issue? What work remains to to be done?

**Comment by jerryaldrichiii** [comment]
I'll leave that to you 😄 

It documents the local dev work flow for Policyfile cookbooks converted to Effortless packages. I believe it is the best workflow for local development (e.g. requires Virtualbox and Vagrant). A non cookbook package doesn't have an example yet, but off the top of my head I'm not sure what would be different. Habitat is Habitat.

**Comment by TheLunaticScripter** [comment]
This has been updated in the latest examples and is being added in the new documentation for Inspec as  well.
