### ISSUE TITLE
[Tracking] Windows bootstrap script for Habitat Windows Service

### ISSUE THREAD

**Issue by andmor** [chef/effortless#65]
Add a powershell script to the bin/bootstrap in the repo that can bootstrap Habitat on Windows.

**Comment by TheLunaticScripter** [comment]
@andmor I'm doing some issue clean up and it looks like we have a `bootstrap.ps1` in the `bin` directory. Can you confirm that this fixes your issue or is there more to be done with this?

**Comment by TheLunaticScripter** [comment]
This appears to be an old issue
