### ISSUE TITLE
[Tracking] [scaffolding-chef-infra] Windows paths in the non-docker studio cause chef export to fail

### ISSUE THREAD

**Issue by echohack** [chef/effortless#86]
For Windows builds, long paths cause `chef export` to fail during the build.

A path might look like this:
`C:/Users/ADMINI~1/AppData/Local/Temp/chefdk-export-3928-2019072317143620190723-3928-nlvye1/cookbook_artifacts/lul_win_security-5ce041cdafceb750d9ca318396c4c4fa411b9b71/files/default/cSecurityOptions/3.1.2/DSCResources/AccountAndBasicAuditing/AccountAndBasicAuditing.psm1`

You can use a Docker studio to avoid this issue for now.

**Comment by gsreynolds** [comment]
You can also set the `CHEF_WORKSTATION_HOME` environment variable 

https://github.com/chef/chef-cli/blob/814b04a24c1ac64ae240fc0e5bbc64b9fd52cb86/lib/chef-cli/helpers.rb#L72-L81

and set a directory to something shorter than the default

https://github.com/chef/chef-cli/blob/814b04a24c1ac64ae240fc0e5bbc64b9fd52cb86/lib/chef-cli/helpers.rb#L142-L148
