### ISSUE TITLE
[scaffolding_chef-inspec]Make verify_ssl a configuration option

### ISSUE THREAD

**Issue by TheLunaticScripter** [chef/effortless#97]
Currently the `inspec_exec_config.json` file has a `verify_ssl` option in it that is set to false. This should be changed to a configuration option with a more secure default of `true`.

**Comment by ericcalabretta** [comment]
Default of true makes sense, as long as it's still configurable for initial testing/pilots where SSL may not be configured yet.

**Comment by echohack** [comment]
@ericcalabretta I don't know if I agree. Forcing SSL is an important piece of hygiene to do FIRST.

We should rather, support methods that make it easy to do SSL by default and solve for those. The CACerts feature is one piece of that. What else do we need to make this easy?

**Comment by ericcalabretta** [comment]
It's reasonable to have SSL for any production install but its not feasible for a lot of evaluations. The constraint will be the individual enterprises cert process & what it takes to get a cert on the Automate Server. It adds a significant effort to any evaluation process which would make getting a prospect to use "effortless" would take some effort ;)

SSL is also not a material thing during evaluations/learning. At that point in the process the goal is to validate the value a specific solution can provide to an organization. The result of any evaluation should also only be the code with the environment and systems being removed & replaced after a production design/implementation process. 

InSpec reporting also isn't the same animal as Chef Infra. The reports data could be sensitive but couldn't give you root access to the client system like with Chef Infra.

**Comment by echohack** [comment]
Every evaluation system of Chef Automate I've ever used has a valid cert. @scottford-io can also weigh in on this. If you need a way to automate this cert process, we have this.

I don't think this is even close to a strong argument to allow us to turn off SSL.
